print('hola\u0020Mundo')
print('Notacion simple:', '\u0041')
print('Notacion extendida:', '\U00000041')
print('Notacion hexadecimal: ', '\x41')
print('Corazon:','\u2665')
print('Cara sonriendo: ', '\U0001f600')
print('Serpierte; ', '\U0001F40D')

#caracteres ASCII
caracter = chr(65)
print('A mayuscula:', caracter)
caracter = chr(64)
print('Simbolo @:', caracter)
caracter = chr(97)
print('a minuscula:', caracter)